source 'https://rubygems.org'
gem 'bcrypt'
gem 'bootstrap'
gem 'rails', '4.2.7'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'pry-rails'
  gem 'table_print'
  gem 'annotate'
  gem 'byebug'
  gem 'faker'
end
