# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02b4d4de9bbe9905a58b41c09f826d24d2550251a3b73a5a1d079481d502cfbc7a37ee39b9fbaff417debf3c2bb3fa06c41c869cee1ceb36132f48ddb3eaffea

test:
  secret_key_base: f16d888ed4800631b416141b5dccb0a98d43e234e6090a43882674a8e32924fcfdf551a56ebe8948a0e78a8f8f50d8ae359c64157ba6d750b204425d6e603f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
